### POST /api/login ###
POST http://localhost:8080/api/login
Content-Type: application/x-www-form-urlencoded

username=test&password=test


### POST /api/employees ###
POST http://localhost:8080/api/employees
Content-Type: application/json
Authorization: your-token-value

{
  "id": "2",
  "username": "test",
  "password": "test",
  "role": "admin"
}

### GET /api/employees ###
GET http://localhost:8080/api/employees
Content-Type: application/json
Authorization: your-token-value

{}

### GET /api/employees/{id} ###
GET http://localhost:8080/api/employees/{id}
Content-Type: application/json
Authorization: your-token-value

### PUT /api/employees/{id} ###
PUT http://localhost:8080/api/employees/{id}
Content-Type: application/json
Authorization: your-token-value

{
  "id": "bc036eb5-6bc5-47e2-bdf7-8734a92412f6",
  "username": "test",
  "password": "test2",
  "role": "admin"
}

### DELETE /api/employees/{id} ###
DELETE http://localhost:8080/api/employees/{id}
Content-Type: application/json
Authorization: Bearer your-token-value
