version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - my-network

volumes:
  mongodb-data:

networks:
  my-network:
